const appConstants = {
  ALERT_ERROR: 'ALERT_ERROR',
  SHOW_ALERT: 'SHOW_ALERT',
  CLOSE_ALERT: 'CLOSE_ALERT',
  ALERT_SUCCESS: 'ALERT_SUCCESS',

  APP_LOADING: 'APP_LOADING',

  SET_LOG_IN: 'SET_LOG_IN',
  SET_LOG_OUT: 'SET_LOG_OUT',
  SIGN_UP_USER: 'SIGN_UP_USER',
  LOGGED_USER: 'LOGGED_USER',
  AUTH_ERROR: 'AUTH_ERROR',

  DRAWER_OPEN: 'DRAWER_OPEN',
  DRAWER_CLOSED: 'DRAWER_CLOSED',

  SET_SEARCH_ITEM: 'SET_SEARCH_ITEM',

};

export default appConstants;
